variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  S3_BUCKET_NAME: "emmanueljreyme.com"

stages:
  - build
  - deploy

job 1:
  stage: build
  image: node
  artifacts:
    paths:
      - dist/emmanueljreymedotcom
  script:
  - npm install -g @angular/cli
  - npm install
  - ng build --prod

job 2:  
  stage: deploy
  image: python:latest
  script:
  - pip install awscli
  - aws s3 rm s3://$S3_BUCKET_NAME --recursive
  - aws s3 cp ./dist/emmanueljreymedotcom s3://$S3_BUCKET_NAME --recursive
